name: jobee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/images/placeholder.png
    - assets/images/female_asian_car.png
    - assets/images/female_asian_office.png
    - assets/images/female_asian_traveller.png
  